apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/selimatmaca/K8sConfiguration.git
    targetRevision: HEAD
    path: 
  destination:
    server: https://kubernetes.default.svc
    #this is the namespace where we will apply our configuration
    namespace: default

  syncPolicy:
    syncOptions:
        #if the namespace is not created already, argocd creates it
      - CreateNamespace=true
    #by default argocd does not apply changes from git repo, we configure it to apply changes automatically
    automated:
      selfHeal: true
      #by default, auto sync does not delete resource, we use prune to do that
      prune: true