apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SQL_USER: ZGJ1c2Vy
  SQL_PASSWORD: ZGJwYXNz
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLS1oMDYtd190dyRAdDJfb15scDNwaXZ2MCUhZzg0biVxZmZ5Xit4YjQ4NCpANSVjQCMw

